#   This .travis.yml works to check "this" repository, namely `industrial_ci`. Do not get confused with the check of "client" repositories (repos that use travis configs in this repo).

#  Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

#sudo: required  # Not required by industrial_ci that uses Docker.
#dist: trusty    # Not required by industrial_ci that uses Docker.
services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic

group: deprecated-2017Q4

env:
  global:
    - BEFORE_SCRIPT='ls -la $HOME/.ssh'

  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=kinetic
script:
  - ls -la ~/.ssh
  - industrial_ci/_wrap_test.sh # this script is only for internal use
