# This .travis.yml works to check "this" repository, namely `industrial_ci`.
# A template for users can be found here: https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml

# Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic
notifications:
  #  Whoever receives success and/or failure via email
  email:
    recipients:
      - gm130s@gmail.com  # Change this to yours should you copy this file.

git:
  quiet: true

env:
  global: []
  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=jade
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=lunar
    - ROS_DISTRO=melodic
    - ROS_DISTRO=kinetic _EXTERNAL_REPO='github:ros-controls/ros_control#kinetic-devel' UPSTREAM_WORKSPACE="ros_control.rosinstall -ros_control -ros_controllers"
    - ROS_DISTRO=melodic _EXTERNAL_REPO='github:ros-controls/ros_control#melodic-devel' UPSTREAM_WORKSPACE="github:ros-controls/control_msgs#kinetic-devel github:ros-controls/realtime_tools#melodic-devel github:ros-controls/control_toolbox#melodic-devel" DOWNSTREAM_WORKSPACE="github:ros-controls/ros_controllers#melodic-devel"
    - ROS_DISTRO=bouncy _EXTERNAL_REPO='github:ros2/joystick_drivers#bouncy'
    - DOCKER_IMAGE=ros:crystal _EXTERNAL_REPO='github:ros-controls/control_msgs#crystal-devel'
matrix:
  allow_failures: []
  include:
    - script: shellcheck -x *.sh industrial_ci/scripts/*_ci industrial_ci/src/*.sh industrial_ci/src/*/*.sh industrial_ci/*.sh
      env: [shellcheck]

script:
  - industrial_ci/_wrap_test.sh # this script is only for internal use
