# This .travis.yml works to check "this" repository, namely `industrial_ci`.
# A template for users can be found here: https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml

# Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic
notifications:
  #  Whoever receives success and/or failure via email
  email:
    recipients:
      - gm130s@gmail.com  # Change this to yours should you copy this file.

git:
  quiet: true

env:
  global: []
  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=jade
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=lunar
    - ROS_DISTRO=melodic
    - ROS_DISTRO=kinetic _EXTERNAL_REPO='ros-controls/ros_control#kinetic-devel' UPSTREAM_WORKSPACE="ros_control.rosinstall -ros_control"
    - ROS_DISTRO=bouncy _EXTERNAL_REPO='ros2/joystick_drivers#bouncy'
matrix:
  allow_failures: []

script:
  - industrial_ci/_wrap_test.sh # this script is only for internal use
